FROM python:3.10-slim-buster
# Install python packages
RUN pip install mlflow==2.3.0
RUN pip install boto3==1.26.121
RUN pip install pymysql
# COPY ./requirements.txt /code/requirements.txt
# RUN pip install -r /code/requirements.txt