FROM python:3.9
# Install python packages
RUN pip install mlflow==2.3.0
RUN pip install jupyter==1.0.0
RUN pip install jupyterlab==3.6.1
RUN pip install pycaret==3.3.0
RUN pip install scikit-learn==1.4.2
RUN pip install scipy==1.11.4
RUN pip install boto3==1.26.121
RUN pip install requests==2.28.2
RUN pip install joblib==1.3.0
# COPY ./requirements.txt /code/requirements.txt
# RUN pip install -r /code/requirements.txt